#!/usr/bin/env bash
set -euo pipefail

# SensibleFox — Build macOS .pkg installer
#
# Produces dist/SensibleFox.pkg. The .pkg ships only the SensibleFox payload
# (policies.json, autoconfig.cfg, userChrome.css, uBO managed storage). At
# install time the postinstall script:
#   • fetches the latest Firefox version
#   • shows the user which version is about to be installed
#   • downloads the matching Firefox.app into /Applications
#   • injects the payload so the install is fully configured
#
# Configurable via environment:
#   INSTALL_LOCATION  Where Firefox.app lands (default: /Applications)
#   FIREFOX_LANG      Firefox locale (default: en-US)
#   PKG_VERSION       Package version (default: 1.0.0)
#   PKG_IDENTIFIER    Package identifier (default: com.sensiblefox.firefox)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DIST_DIR="$ROOT_DIR/dist"
ASSETS_DIR="$ROOT_DIR/assets"
GEN_DIR="$ROOT_DIR/generated"
PKG_ROOT="$DIST_DIR/pkg-root"
SCRIPTS_DIR="$DIST_DIR/pkg-scripts"

INSTALL_LOCATION="${INSTALL_LOCATION:-/Applications}"
FIREFOX_LANG="${FIREFOX_LANG:-en-US}"
PKG_VERSION="${PKG_VERSION:-1.0.0}"
PKG_IDENTIFIER="${PKG_IDENTIFIER:-com.sensiblefox.firefox}"
PAYLOAD_DIR="/Library/Application Support/SensibleFox/payload"

echo "SensibleFox: building installer .pkg"
echo "===================================="
echo "  install location : $INSTALL_LOCATION"
echo "  locale           : $FIREFOX_LANG"
echo "  version          : $PKG_VERSION"
echo ""

if [ ! -f "$GEN_DIR/sensiblefox-defaults.js" ]; then
    echo "  ✗ generated/sensiblefox-defaults.js missing."
    echo "    Run: ./scripts/generate-prefs.sh"
    exit 1
fi

for f in policies.json autoconfig.js sensiblefox.cfg.tail uBlock0@raymondhill.net.json; do
    if [ ! -f "$ASSETS_DIR/$f" ]; then
        echo "  ✗ assets/$f missing."
        exit 1
    fi
done

echo "  → Cleaning previous build..."
rm -rf "$PKG_ROOT" "$SCRIPTS_DIR" "$DIST_DIR/SensibleFox.pkg" "$DIST_DIR/sensiblefox.pkg"
mkdir -p "$PKG_ROOT$PAYLOAD_DIR" "$SCRIPTS_DIR"

echo "  → Staging payload assets..."
cp "$ASSETS_DIR/policies.json" "$PKG_ROOT$PAYLOAD_DIR/policies.json"
cp "$ASSETS_DIR/autoconfig.js" "$PKG_ROOT$PAYLOAD_DIR/autoconfig.js"
cp "$ASSETS_DIR/uBlock0@raymondhill.net.json" "$PKG_ROOT$PAYLOAD_DIR/uBlock0@raymondhill.net.json"

{
    cat "$GEN_DIR/sensiblefox-defaults.js"
    cat "$ASSETS_DIR/sensiblefox.cfg.tail"
} > "$PKG_ROOT$PAYLOAD_DIR/sensiblefox.cfg"

{
    echo "/* SensibleFox bundled userChrome — generated by build-pkg.sh */"
    for f in macos-native-tabbar.css \
             ublock_icon_change.css \
             cleaner_extensions_menu.css \
             no_search_engines_in_url_bar.css \
             privacy_change_email_text.css \
             show_searchbar_dots_only_on_hover.css \
             context_menu_cleanup.css; do
        if [ -f "$ASSETS_DIR/$f" ]; then
            echo ""
            echo "/* ── $f ── */"
            cat "$ASSETS_DIR/$f"
        fi
    done
} > "$PKG_ROOT$PAYLOAD_DIR/userChrome.css"

echo "  → Staging system-wide uBO managed storage..."
MANAGED_DIR="$PKG_ROOT/Library/Application Support/Mozilla/ManagedStorage"
mkdir -p "$MANAGED_DIR"
cp "$ASSETS_DIR/uBlock0@raymondhill.net.json" "$MANAGED_DIR/uBlock0@raymondhill.net.json"

echo "  → Writing preinstall (version preview)..."
cat > "$SCRIPTS_DIR/preinstall" <<PREINSTALL
#!/usr/bin/env bash
set -e

VERSION_URL="https://product-details.mozilla.org/1.0/firefox_versions.json"
VERSION="\$(curl -fsSL --max-time 10 "\$VERSION_URL" 2>/dev/null \\
    | /usr/bin/sed -n 's/.*"LATEST_FIREFOX_VERSION"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' \\
    | head -1)"
[ -z "\$VERSION" ] && VERSION="latest"

echo ""
echo "──────────────────────────────────────────────"
echo "  SensibleFox will install Firefox \$VERSION"
echo "──────────────────────────────────────────────"
echo ""

CONSOLE_USER="\$(/usr/bin/stat -f%Su /dev/console 2>/dev/null || true)"
if [ -n "\$CONSOLE_USER" ] && [ "\$CONSOLE_USER" != "root" ]; then
    /bin/launchctl asuser "\$(/usr/bin/id -u "\$CONSOLE_USER")" /usr/bin/sudo -u "\$CONSOLE_USER" \\
        /usr/bin/osascript -e "display notification \"Installing Firefox \$VERSION\" with title \"SensibleFox\"" \\
        >/dev/null 2>&1 || true
fi

exit 0
PREINSTALL
chmod 755 "$SCRIPTS_DIR/preinstall"

echo "  → Writing postinstall (download + configure)..."
cat > "$SCRIPTS_DIR/postinstall" <<POSTINSTALL
#!/usr/bin/env bash
set -e

PAYLOAD="$PAYLOAD_DIR"
APP="$INSTALL_LOCATION/Firefox.app"
FF_LANG="$FIREFOX_LANG"
DMG_URL="https://download.mozilla.org/?product=firefox-latest-ssl&os=osx&lang=\$FF_LANG"

VERSION_URL="https://product-details.mozilla.org/1.0/firefox_versions.json"
VERSION="\$(curl -fsSL --max-time 10 "\$VERSION_URL" 2>/dev/null \\
    | /usr/bin/sed -n 's/.*"LATEST_FIREFOX_VERSION"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' \\
    | head -1)"
[ -z "\$VERSION" ] && VERSION="latest"

echo "SensibleFox: downloading Firefox \$VERSION..."

TMP="\$(mktemp -d -t sensiblefox)"
trap 'rm -rf "\$TMP"' EXIT
DMG="\$TMP/Firefox.dmg"

curl -fSL "\$DMG_URL" -o "\$DMG"

MOUNT="\$(/usr/bin/hdiutil attach -nobrowse -noautoopen "\$DMG" \\
    | awk '/\\/Volumes\\// { for (i=3; i<=NF; ++i) printf "%s%s", \$i, (i==NF ? "" : " ") }' \\
    | tail -n1)"
if [ -z "\$MOUNT" ] || [ ! -d "\$MOUNT" ]; then
    MOUNT="\$(ls -d /Volumes/Firefox* 2>/dev/null | head -1)"
fi
if [ -z "\$MOUNT" ] || [ ! -d "\$MOUNT" ]; then
    echo "SensibleFox: could not mount Firefox DMG"
    exit 1
fi

if [ -d "\$APP" ]; then
    rm -rf "\$APP"
fi
/usr/bin/ditto "\$MOUNT/Firefox.app" "\$APP"
/usr/bin/hdiutil detach -quiet "\$MOUNT" || true

/usr/bin/xattr -r -d com.apple.quarantine "\$APP" 2>/dev/null || true

RES="\$APP/Contents/Resources"
mkdir -p "\$RES/distribution" "\$RES/defaults/pref" "\$RES/sensiblefox"
cp "\$PAYLOAD/policies.json"   "\$RES/distribution/policies.json"
cp "\$PAYLOAD/autoconfig.js"   "\$RES/defaults/pref/autoconfig.js"
cp "\$PAYLOAD/sensiblefox.cfg" "\$RES/sensiblefox.cfg"
cp "\$PAYLOAD/userChrome.css"  "\$RES/sensiblefox/userChrome.css"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  SensibleFox installed Firefox \$VERSION"
echo "║  Launch Firefox — fully configured."
echo "╚══════════════════════════════════════════════╝"
echo ""
exit 0
POSTINSTALL
chmod 755 "$SCRIPTS_DIR/postinstall"

echo "  → Building .pkg..."
pkgbuild \
    --root "$PKG_ROOT" \
    --scripts "$SCRIPTS_DIR" \
    --identifier "$PKG_IDENTIFIER" \
    --version "$PKG_VERSION" \
    --install-location "/" \
    "$DIST_DIR/SensibleFox.pkg" \
    > /dev/null

rm -rf "$PKG_ROOT" "$SCRIPTS_DIR"

SIZE=$(du -h "$DIST_DIR/SensibleFox.pkg" | cut -f1 | tr -d ' ')
echo ""
echo "  ✓ Built dist/SensibleFox.pkg ($SIZE)"
echo "    Install: open dist/SensibleFox.pkg"
echo "    Or:      sudo installer -pkg dist/SensibleFox.pkg -target /"
