#!/usr/bin/env bash
set -euo pipefail

# sensiblefox — Build macOS .pkg installer
#
# Produces dist/sensiblefox.pkg containing a complete, pre-configured
# Firefox.app at $INSTALL_LOCATION (default /Applications). The bundled
# Firefox carries:
#   • distribution/policies.json       — enterprise policies (uBO auto-install,
#                                        telemetry off, DoH, etc.)
#   • defaults/pref/autoconfig.js      — sentinel that bootstraps autoconfig
#   • sensiblefox.cfg                  — autoconfig script: ~800 defaultPref()
#                                        calls + global CSS injection. This is
#                                        the canonical Mozilla-supported path
#                                        for shipping default prefs (modern
#                                        Firefox ignores arbitrary .js files
#                                        in defaults/pref/).
#   • sensiblefox/userChrome.css       — bundled CSS loaded as AGENT_SHEET
#
# The .pkg installs Firefox only — it does NOT include the sensiblefox CLI.
# The CLI is a developer/iteration tool built separately via `cargo build`.
#
# Configurable via environment:
#   INSTALL_LOCATION  Where Firefox.app lands (default: /Applications)
#   FIREFOX_LANG      Firefox locale (default: en-US)
#   PKG_VERSION       Package version (default: 1.0.0)
#   PKG_IDENTIFIER    Package identifier (default: com.sensiblefox.firefox)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DIST_DIR="$ROOT_DIR/dist"
ASSETS_DIR="$ROOT_DIR/assets"
GEN_DIR="$ROOT_DIR/generated"
STAGING_DIR="$DIST_DIR/staging"
PKG_ROOT="$DIST_DIR/pkg-root"
SCRIPTS_DIR="$DIST_DIR/pkg-scripts"

INSTALL_LOCATION="${INSTALL_LOCATION:-/Applications}"
FIREFOX_LANG="${FIREFOX_LANG:-en-US}"
PKG_VERSION="${PKG_VERSION:-1.0.0}"
PKG_IDENTIFIER="${PKG_IDENTIFIER:-com.sensiblefox.firefox}"
FIREFOX_DMG_URL="https://download.mozilla.org/?product=firefox-latest-ssl&os=osx&lang=$FIREFOX_LANG"

echo "sensiblefox: building Firefox installer .pkg"
echo "============================================"
echo "  install location : $INSTALL_LOCATION"
echo "  locale           : $FIREFOX_LANG"
echo "  version          : $PKG_VERSION"
echo ""

if [ ! -f "$GEN_DIR/sensiblefox-defaults.js" ]; then
    echo "  ✗ generated/sensiblefox-defaults.js missing."
    echo "    Run: ./scripts/generate-prefs.sh"
    exit 1
fi

for f in policies.json autoconfig.js sensiblefox.cfg.tail uBlock0@raymondhill.net.json; do
    if [ ! -f "$ASSETS_DIR/$f" ]; then
        echo "  ✗ assets/$f missing."
        exit 1
    fi
done

echo "  → Cleaning previous build..."
rm -rf "$STAGING_DIR" "$PKG_ROOT" "$SCRIPTS_DIR" "$DIST_DIR/sensiblefox.pkg"
mkdir -p "$STAGING_DIR" "$PKG_ROOT$INSTALL_LOCATION" "$SCRIPTS_DIR"

DMG_PATH="$STAGING_DIR/Firefox.dmg"
echo "  → Downloading Firefox ($FIREFOX_LANG)..."
curl -fSL --progress-bar "$FIREFOX_DMG_URL" -o "$DMG_PATH"

echo "  → Mounting DMG..."
MOUNT_POINT="$(hdiutil attach -nobrowse -noautoopen "$DMG_PATH" \
    | awk '/\/Volumes\// { for (i=3; i<=NF; ++i) printf "%s%s", $i, (i==NF ? "" : " ") }' \
    | tail -n1)"
if [ -z "$MOUNT_POINT" ] || [ ! -d "$MOUNT_POINT" ]; then
    MOUNT_POINT="$(ls -d /Volumes/Firefox* 2>/dev/null | head -1)"
fi
if [ -z "$MOUNT_POINT" ] || [ ! -d "$MOUNT_POINT" ]; then
    echo "  ✗ Could not locate Firefox DMG mount point"
    exit 1
fi
trap 'hdiutil detach -quiet "$MOUNT_POINT" 2>/dev/null || true' EXIT

echo "  → Copying Firefox.app to staging..."
ditto "$MOUNT_POINT/Firefox.app" "$STAGING_DIR/Firefox.app"

echo "  → Detaching DMG..."
hdiutil detach -quiet "$MOUNT_POINT"
trap - EXIT

echo "  → Removing quarantine attribute..."
xattr -r -d com.apple.quarantine "$STAGING_DIR/Firefox.app" 2>/dev/null || true

RES_DIR="$STAGING_DIR/Firefox.app/Contents/Resources"

echo "  → Injecting policies.json..."
mkdir -p "$RES_DIR/distribution"
cp "$ASSETS_DIR/policies.json" "$RES_DIR/distribution/policies.json"

echo "  → Injecting autoconfig sentinel..."
mkdir -p "$RES_DIR/defaults/pref"
cp "$ASSETS_DIR/autoconfig.js" "$RES_DIR/defaults/pref/autoconfig.js"

echo "  → Assembling sensiblefox.cfg (defaults + CSS injection)..."
{
    cat "$GEN_DIR/sensiblefox-defaults.js"
    cat "$ASSETS_DIR/sensiblefox.cfg.tail"
} > "$RES_DIR/sensiblefox.cfg"

echo "  → Bundling CSS payload..."
mkdir -p "$RES_DIR/sensiblefox"
{
    echo "/* sensiblefox bundled userChrome — generated by build-pkg.sh */"
    for f in macos-native-tabbar.css \
             sliding-bookmarks-menu.css \
             ublock_icon_change.css \
             cleaner_extensions_menu.css \
             no_search_engines_in_url_bar.css \
             privacy_change_email_text.css \
             show_searchbar_dots_only_on_hover.css \
             context_menu_cleanup.css; do
        if [ -f "$ASSETS_DIR/$f" ]; then
            echo ""
            echo "/* ── $f ── */"
            cat "$ASSETS_DIR/$f"
        fi
    done
} > "$RES_DIR/sensiblefox/userChrome.css"

echo "  → Staging payload at $INSTALL_LOCATION..."
ditto "$STAGING_DIR/Firefox.app" "$PKG_ROOT$INSTALL_LOCATION/Firefox.app"

echo "  → Staging uBlock managed storage (system-wide)..."
MANAGED_DIR="$PKG_ROOT/Library/Application Support/Mozilla/ManagedStorage"
mkdir -p "$MANAGED_DIR"
cp "$ASSETS_DIR/uBlock0@raymondhill.net.json" "$MANAGED_DIR/uBlock0@raymondhill.net.json"

echo "  → Writing postinstall..."
cat > "$SCRIPTS_DIR/postinstall" << 'POSTINSTALL'
#!/usr/bin/env bash
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  sensiblefox installed.                      ║"
echo "║  Launch Firefox — fully configured.          ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
exit 0
POSTINSTALL
chmod 755 "$SCRIPTS_DIR/postinstall"

echo "  → Building .pkg..."
pkgbuild \
    --root "$PKG_ROOT" \
    --scripts "$SCRIPTS_DIR" \
    --identifier "$PKG_IDENTIFIER" \
    --version "$PKG_VERSION" \
    --install-location "/" \
    "$DIST_DIR/sensiblefox.pkg" \
    > /dev/null

rm -rf "$STAGING_DIR" "$PKG_ROOT" "$SCRIPTS_DIR"

SIZE=$(du -h "$DIST_DIR/sensiblefox.pkg" | cut -f1 | tr -d ' ')
echo ""
echo "  ✓ Built dist/sensiblefox.pkg ($SIZE)"
echo "    Install: open dist/sensiblefox.pkg"
echo "    Or:      sudo installer -pkg dist/sensiblefox.pkg -target /"
